### ISSUE TITLE
Location permission check always true

### ISSUE THREAD

**Issue by shlusiak** [a-ton/gpd-bot#9]
See https://github.com/a-ton/gpd-bot/blob/6547106d0e0a26468ce649d1bbb551526c0bb0e8/permissions_getter.py#L31-L32

The boolean check for the location permission always evaluates to True, because the first part of the or is only a truthy string.

```py
if "truthy" or "needle" in ["notyourhay"]:
    print "this will return true"
```

As a result, every single APK will be listed as requiring Location permission, which is not true.

**Comment by a-ton** [comment]
Thanks so much for noticing this! I've fixed the issue and am updating the bot now.
